Messages:
  Comandos:
    no-permission: '&cVocê não tem permissão para usar este comando!'
    argument-not-found: '&cArgumento não encontrado! Digite &f/terrenos &cpara ver a lista de comandos!'
    too-many-arguments: '&cVocê não pode colocar espaços aqui!'
    Terrenos:
      - ' '
      - '&3/terreno comprar&f: Compre o seu terreno.'
      - '&3/terreno abandonar&f: Abandone o seu terreno.'
      - '&3/terreno add <player>&f: Adicione um amigo em seu terreno.'
      - '&3/terreno remover <player>&f: Remove um player do seu terreno.'
      - '&3/terreno pvp <ativado/desativado>&f: Ativa/Desativa o pvp do seu terreno.'
      - '&3/terreno info&f: Mostra as informações do terreno em sua localização.'
      - '&3/terreno upgrade&f: Faça um upgrade no tamnaho do seu terreno.'
      - ' '
    Comprar:
      you-already-have-a-terrain: '&cVocê já tem um terreno!'
      you-are-on-exisisting-terrain: '&cVocê já está em um terreno!'
      close-to-a-terrain: '&cVocê está muito perto de outro terreno!'
      you-dont-have-money: '&cVocê não tem dinheiro suficiente para comprar esse terreno!'
      mini-successful-buy-message: '&3Terreno &fMINI &3adquirido com sucesso!'
      pequeno-successful-buy-message: '&3Terreno &fPEQUENO &3adquirido com sucesso!'
      medio-successful-buy-message: '&3Terreno &fMEDIO &3adquirido com sucesso!'
      grande-successful-buy-message: '&3Terreno &fGRANDE &3adquirido com sucesso!'
      gigante-successful-buy-message: '&3Terreno &fGIGANTE &3adquirido com sucesso!'
    Info:
      there-is-not-a-terrain-here: '&cNão há nenhum terreno nesta localização!'
    Add:
      missing-one-argument: '&cDigite &f/terreno add <player>&c!'
      you-dont-have-a-terrain: '&cVocê não tem nenhum terreno!'
      target-offline: '&cEste jogador está Offline!'
      add-yourself: '&cVocê já está adicionado em seu terreno!'
      you-have-to-be-on-your-terrain: '&cVocê deve estar no seu terreno para adicionar amigos!'
      successful-you-were-added-message: '&3Você foi adicionado no terreno de &f{FRIEND}&3!'
      successful-add-friend-message: '&3Você adicionou &f{FRIEND} &3em seu terreno!'
      player-already-in-terrains-friends-list: '&cEste player já está adicionado neste terreno!'
    Remover:
      missing-one-argument: '&cDigite &f/terreno remover <player>&c!'
      you-dont-have-a-terrain: '&cVocê não tem um terreno!'
      target-offline: '&cEste jogador está Offline!'
      remove-yourself: '&cVocê não pode se remover do seu terreno! Use &f/terreno abandonar &cpara deixar seu terreno!'
      you-have-to-be-on-your-terrain: '&cVocê deve estar no seu terreno para remover amigos!'
      player-not-in-terrains-friends-list: '&cEste player não está na lista de amigos deste terreno!'
      successful-you-were-removed-message: '&3Você foi removido do terreno de &f{FRIEND}&3!'
      successful-remove-friend-message: '&3Você removeu &f{FRIEND} &3do seu terreno!'
    Abandonar:
      you-dont-have-a-terrain: '&cVocê não tem nenhum terreno!'
      successful-leave-terrain-message: '&3Terreno abandonado com sucesso!'
    Pvp:
      missing-one-argument: '&cDigite &f/pvp <ativado/desativado>&c!'
      wrong-argument: '&cO PVP pode ser apenas ativado ou desativado!'
      you-dont-have-a-terrain: '&cVocê não tem um terreno!'
      already-on: '&cO PVP já está ativo neste terreno!'
      already-off: '&cO PVP já está desativado neste terreno!'
      successful-turn-on: '&3O PVP foi ativado neste terreno!'
      successful-turn-off: '&3O PVP foi desativado neste terreno!'
    Upgrade:
      you-have-to-be-on-your-terrain: '&cVocê só pode usar &f/terreno &cupgrade dentro do seu terreno!'
      you-already-have-this-type-of-terrain: '&cVocê já possui este terreno!'
      you-already-have-a-better-terrain: '&cVocê já possui um terreno superior a este!'
      you-dont-have-money: '&cVocê não tem dinheiro suficiente para dar upgrade para este terreno!'
      you-are-not-the-owner: '&cVocê não é o dono deste terreno!'
      pequeno-successful-buy-message: '&3Terreno &fPEQUENO &3adquirido com sucesso!'
      medio-successful-buy-message: '&3Terreno &fMEDIO &3adquirido com sucesso!'
      grande-successful-buy-message: '&3Terreno &fGRANDE &3adquirido com sucesso!'
      gigante-successful-buy-message: '&3Terreno &fGIGANTE &3adquirido com sucesso!'
  Events:
    pvp: '&cO PVP está desativado neste terreno!'
    interact: '&cVocê não pode interagir com nada neste terreno'
    build-limit: '&cVocê só pode colocar blocos até &f320 &cblocos de altura'
Permissions:
  all: 'specialterrains.all'
  buy: 'specialterrains.buy'
  leave: 'specialterrains.leave'
  add: 'specialterrains.add'
  remove: 'specialterrains.remove'
  pvp: 'specialterrains.pvp'
  info: 'specialterrains.info'
  upgrade: 'specialterrains.upgrade'
  admin: 'specialterrains.admin'